package com.wqst.api.caseorder;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import com.wqst.api.account.mapper.UserAccountMapper;
import com.wqst.api.account.entity.UserAccountEntity;
import com.wqst.api.audit.AuditService;
import com.wqst.api.caseorder.entity.MaterialSubmissionEntity;
import com.wqst.api.caseorder.entity.ServiceCaseEntity;
import com.wqst.api.caseorder.mapper.*;
import com.wqst.api.catalog.CatalogService;
import com.wqst.api.catalog.entity.MaterialTemplateEntity;
import com.wqst.api.catalog.entity.MaterialTemplateItemEntity;
import com.wqst.api.catalog.entity.ServiceProductEntity;
import com.wqst.api.common.*;
import com.wqst.api.company.CompanyService;
import com.wqst.api.company.entity.CompanyEntity;
import com.wqst.api.company.mapper.CompanyUserMapper;
import com.wqst.api.notification.NotificationService;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class CaseServiceTest {
    ServiceCaseMapper cases=mock(ServiceCaseMapper.class);MaterialSubmissionMapper materials=mock(MaterialSubmissionMapper.class);InvoiceInfoMapper invoices=mock(InvoiceInfoMapper.class);CaseStatusLogMapper statusLogs=mock(CaseStatusLogMapper.class);SupplementRequestMapper supplements=mock(SupplementRequestMapper.class);CompanyUserMapper memberships=mock(CompanyUserMapper.class);CompanyService companies=mock(CompanyService.class);CatalogService catalog=mock(CatalogService.class);CryptoService crypto=mock(CryptoService.class);IdempotencyService idempotency=mock(IdempotencyService.class);AuditService audit=mock(AuditService.class);UserAccountMapper users=mock(UserAccountMapper.class);NotificationService notifications=mock(NotificationService.class);CaseService service;List<MaterialSubmissionEntity> saved;
    @BeforeEach void setup(){service=new CaseService(cases,materials,invoices,statusLogs,supplements,memberships,companies,catalog,crypto,new CaseStateMachine(),idempotency,audit,users,notifications);saved=new ArrayList<>();AtomicLong ids=new AtomicLong(100);doAnswer(i->{ServiceCaseEntity c=i.getArgument(0);c.setId(1L);c.setVersion(0);return 1;}).when(cases).insert(any(ServiceCaseEntity.class));doAnswer(i->{MaterialSubmissionEntity m=i.getArgument(0);m.setId(ids.incrementAndGet());m.setVersion(0);saved.add(m);return 1;}).when(materials).insert(any(MaterialSubmissionEntity.class));when(materials.selectList(any())).thenAnswer(i->saved);when(invoices.selectOne(any())).thenReturn(null);}
    @Test void createsTradeDraftWithElevenSnapshotItems(){CompanyEntity company=new CompanyEntity();company.setId(2L);company.setCompanyName("示例公司");when(companies.require(2)).thenReturn(company);ServiceProductEntity product=new ServiceProductEntity();product.setId(3L);product.setTemplateId(4L);product.setStatus("PUBLISHED");when(catalog.requireProduct(3)).thenReturn(product);MaterialTemplateEntity template=new MaterialTemplateEntity();template.setTemplateCode("TRADE_INCREMENT");when(catalog.requireTemplate(4)).thenReturn(template);List<MaterialTemplateItemEntity> templateItems=new ArrayList<>();for(int i=1;i<=11;i++){MaterialTemplateItemEntity item=new MaterialTemplateItemEntity();item.setId((long)i);item.setItemCode("M"+i);item.setItemName("资料"+i);item.setInputType(i==11?"URL":"FILE");item.setIsRequired(true);item.setIsSensitive(i>2);templateItems.add(item);}when(catalog.templateItems(4)).thenReturn(templateItems);CaseService.CaseView result=service.createTransaction(new CaseService.CreateCase(2,3,"TRADE_INCREMENT","2026-09"),9);assertThat(result.status()).isEqualTo("DRAFT");assertThat(result.progress().total()).isEqualTo(11);assertThat(saved).allSatisfy(m->{assertThat(m.getSubmitStatus()).isEqualTo("NOT_SUBMITTED");assertThat(m.getReviewStatus()).isEqualTo("PENDING");});verify(companies).requireClientAccess(2,9);verify(statusLogs).insert(any(com.wqst.api.caseorder.entity.CaseStatusLogEntity.class));}
    @Test void rejectsProductServiceMismatch(){CompanyEntity company=new CompanyEntity();company.setId(2L);when(companies.require(2)).thenReturn(company);ServiceProductEntity product=new ServiceProductEntity();product.setTemplateId(4L);product.setStatus("PUBLISHED");when(catalog.requireProduct(3)).thenReturn(product);MaterialTemplateEntity template=new MaterialTemplateEntity();template.setTemplateCode("IP_SIMPLE");when(catalog.requireTemplate(4)).thenReturn(template);assertThatThrownBy(()->service.createTransaction(new CaseService.CreateCase(2,3,"TRADE_INCREMENT","2026-09"),9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("SERVICE_PRODUCT_MISMATCH");verify(cases,never()).insert(any(ServiceCaseEntity.class));}
    @Test void refusesSubmitWhenRequiredMaterialMissing(){ServiceCaseEntity c=draft();MaterialSubmissionEntity m=material("NOT_SUBMITTED");saved.add(m);when(cases.selectById(1L)).thenReturn(c);assertThatThrownBy(()->service.submitTransaction(1,9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("MATERIAL_REQUIRED");verify(cases,never()).updateById(any(ServiceCaseEntity.class));}
    @Test void submitsCompleteDraftAndWritesStatus(){ServiceCaseEntity c=draft();saved.add(material("SUBMITTED"));when(cases.selectById(1L)).thenReturn(c);when(cases.updateById(any(ServiceCaseEntity.class))).thenReturn(1);when(supplements.selectList(any())).thenReturn(List.of());CaseService.CaseView result=service.submitTransaction(1,9);assertThat(result.status()).isEqualTo("PENDING_REVIEW");assertThat(c.getSubmittedAt()).isNotNull();verify(statusLogs).insert(argThat((com.wqst.api.caseorder.entity.CaseStatusLogEntity log)->"PENDING_REVIEW".equals(log.getAfterStatus())));}
    @Test void validatesAndSavesUrlMaterial(){ServiceCaseEntity c=draft();MaterialSubmissionEntity m=material("NOT_SUBMITTED");m.setInputType("URL");when(cases.selectById(1L)).thenReturn(c);when(materials.selectById(10L)).thenReturn(m);when(materials.updateById(any(MaterialSubmissionEntity.class))).thenReturn(1);CaseService.MaterialView result=service.saveText(1,10," https://example.invalid/report ",9);assertThat(result.textValue()).isEqualTo("https://example.invalid/report");assertThatThrownBy(()->service.saveText(1,10,"file://local",9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("MATERIAL_URL_INVALID");assertThatThrownBy(()->service.saveText(1,10," ",9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("MATERIAL_VALUE_REQUIRED");}
    @Test void rejectsTextForFileMaterial(){ServiceCaseEntity c=draft();MaterialSubmissionEntity m=material("NOT_SUBMITTED");m.setInputType("FILE");when(cases.selectById(1L)).thenReturn(c);when(materials.selectById(10L)).thenReturn(m);assertThatThrownBy(()->service.saveText(1,10,"abc",9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("MATERIAL_INPUT_INVALID");}
    @Test void savesSimpleFormAndEnforcesConsent(){ServiceCaseEntity c=draft();when(cases.selectById(1L)).thenReturn(c);when(cases.updateById(any(ServiceCaseEntity.class))).thenReturn(1);MaterialSubmissionEntity m=material("NOT_SUBMITTED");when(materials.selectOne(any())).thenReturn(m);when(materials.updateById(any(MaterialSubmissionEntity.class))).thenReturn(1);when(crypto.encrypt(anyString())).thenReturn("cipher");when(crypto.hash(anyString())).thenReturn("hash");when(crypto.maskPhone(anyString())).thenReturn("138 **** 0000");assertThatThrownBy(()->service.saveSimple(1,new CaseService.SimpleCommand("法人","公司","13800000000",false),9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("CONSENT_REQUIRED");CaseService.CaseView result=service.saveSimple(1,new CaseService.SimpleCommand("法人","公司","13800000000",true),9);assertThat(result.legalPersonName()).isEqualTo("法人");assertThat(result.contactPhoneMask()).isEqualTo("138 **** 0000");}
    @Test void rejectsSimpleFormForTradeCase(){ServiceCaseEntity c=draft();c.setServiceType("TRADE_INCREMENT");when(cases.selectById(1L)).thenReturn(c);assertThatThrownBy(()->service.saveSimple(1,new CaseService.SimpleCommand("法人","公司","13800000000",true),9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("SIMPLE_FORM_NOT_APPLICABLE");}
    @Test void savesEncryptedInvoiceAndMarksMaterial(){ServiceCaseEntity c=draft();c.setServiceType("TRADE_INCREMENT");when(cases.selectById(1L)).thenReturn(c);MaterialSubmissionEntity m=material("NOT_SUBMITTED");when(materials.selectOne(any())).thenReturn(m);when(materials.updateById(any(MaterialSubmissionEntity.class))).thenReturn(1);when(crypto.encrypt(anyString())).thenReturn("cipher");when(crypto.hash(anyString())).thenReturn("hash");when(crypto.maskPhone(anyString())).thenReturn("phone-mask");when(crypto.maskTaxNo(anyString())).thenReturn("tax-mask");when(crypto.maskAccount(anyString())).thenReturn("account-mask");CaseService.InvoiceView view=service.saveInvoice(1,new CaseService.InvoiceCommand("公司","91430100123456789X","地址","13800000000","法人","a@example.com","银行","62220000"),9);assertThat(view.taxNoMask()).isEqualTo("tax-mask");verify(invoices).insert(any(com.wqst.api.caseorder.entity.InvoiceInfoEntity.class));}
    @Test void rejectsInvoiceForSimpleService(){ServiceCaseEntity c=draft();when(cases.selectById(1L)).thenReturn(c);assertThatThrownBy(()->service.saveInvoice(1,new CaseService.InvoiceCommand("公司","税号","地址","电话","法人","邮箱","银行","账号"),9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("INVOICE_NOT_APPLICABLE");}
    @Test void validatesFileMaterialBeforeMarkingSubmitted(){MaterialSubmissionEntity m=material("NOT_SUBMITTED");m.setInputType("FILE");when(materials.selectById(10L)).thenReturn(m);when(materials.updateById(any(MaterialSubmissionEntity.class))).thenReturn(1);service.markFileSubmitted(1,10);assertThat(m.getSubmitStatus()).isEqualTo("SUBMITTED");m.setCaseId(99L);assertThatThrownBy(()->service.markFileSubmitted(1,10)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("MATERIAL_INPUT_INVALID");}
    @Test void validatesAssigneeAccount(){ServiceCaseEntity c=draft();when(cases.selectById(1L)).thenReturn(c);assertThatThrownBy(()->service.assign(1,20,9)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("ASSIGNEE_INVALID");UserAccountEntity admin=new UserAccountEntity();admin.setId(20L);admin.setAccountType("ADMIN");admin.setStatus("ENABLED");when(users.selectById(20L)).thenReturn(admin);when(cases.updateById(any(ServiceCaseEntity.class))).thenReturn(1);CaseService.CaseView result=service.assign(1,20,9);assertThat(result.assigneeId()).isEqualTo(20L);}
    @Test void reportsMissingCaseAndMaterial(){assertThatThrownBy(()->service.require(999)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("CASE_NOT_FOUND");assertThatThrownBy(()->service.requireMaterial(999)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("MATERIAL_NOT_FOUND");}
    @Test void timelineOnlyExposesSupplementNote(){ServiceCaseEntity c=draft();when(cases.selectById(1L)).thenReturn(c);com.wqst.api.caseorder.entity.CaseStatusLogEntity supplement=new com.wqst.api.caseorder.entity.CaseStatusLogEntity();supplement.setAfterStatus("NEED_SUPPLEMENT");supplement.setNote("请补资料");com.wqst.api.caseorder.entity.CaseStatusLogEntity internal=new com.wqst.api.caseorder.entity.CaseStatusLogEntity();internal.setAfterStatus("PROCESSING");internal.setNote("内部办理备注");when(statusLogs.selectList(any())).thenReturn(List.of(supplement,internal));List<CaseService.TimelineView> timeline=service.timeline(1,9);assertThat(timeline.get(0).note()).isEqualTo("请补资料");assertThat(timeline.get(1).note()).isNull();}
    private ServiceCaseEntity draft(){ServiceCaseEntity c=new ServiceCaseEntity();c.setId(1L);c.setCompanyId(2L);c.setCaseNo("BD1");c.setCompanyNameSnapshot("示例公司");c.setServiceType("IP");c.setStatus("DRAFT");c.setVersion(0);return c;}
    private MaterialSubmissionEntity material(String status){MaterialSubmissionEntity m=new MaterialSubmissionEntity();m.setId(10L);m.setCaseId(1L);m.setMaterialCode("M1");m.setMaterialName("资料");m.setInputType("TEXT");m.setRequired(true);m.setIsSensitive(false);m.setSubmitStatus(status);m.setReviewStatus("PENDING");m.setVersion(0);return m;}
}
